# Generated by Django 6.0.2 on 2026-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, help_text='Company providing the training if applicable.', max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_range', models.CharField(blank=True, help_text='e.g. Summer 2024', max_length=100, null=True)),
            ],
        ),
    ]
